pipeline {
    agent {
        label 'ubuntu-latest' // ou o nome do seu agente Jenkins
    }
    triggers {
        cron('0 8 * * *') // programar o job para rodar às 8h da manhã todos os dias
    }
    stages {
        stage('Checkout do código') {
            steps {
                script {
                    checkout([$class: 'GitSCM',
                        branches: [[name: '*/master']],
                        doGenerateSubmoduleConfigurations: false,
                        extensions: [[$class: 'CleanBeforeCheckout']],
                        submoduleCfg: [],
                        userRemoteConfigs: [[url: 'https://github.com/samfreitasxs/cypress-ci-cd.git']]
                    ])
                }
            }
        }

        stage('Configurar o Node.js') {
            steps {
                script {
                    // Configurações para instalar o Node.js
                }
            }
        }

        stage('Instalar as dependências') {
            steps {
                script {
                    sh 'npm install'
                }
            }
        }

        stage('Executar os testes') {
            steps {
                script {
                    sh 'npx cypress run'
                }
            }
        }
    }
}
