pipeline {
    agent any

    stages {
        stage('Inicial') {
            steps {
                echo 'Iniciando a pipeline'
            }
        }
        stage('Checkout do codigo') {
            steps {
                // Clonar o repositório do Git
                checkout scm
            }
        }
        stage('Instalar Node.js') {
            steps {
                // Instalar Node.js manualmente
                sh '''
                curl -sL https://deb.nodesource.com/setup_20.x | sudo -E bash -
                sudo apt-get install -y nodejs
                node -v
                npm -v
                '''
            }
        }
        stage('Instalar as dependencias') {
            steps {
                // Instalar dependências do projeto
                sh 'npm install'
            }
        }
        stage('Executar os testes') {
            steps {
                // Executar testes do Cypress
                sh 'npx cypress run'
            }
        }
    }
}
